### ISSUE TITLE
Closing incoming stream doesn't yield None from Framed

### ISSUE THREAD

**Issue by Nemo157** [matthunz/futures-codec#1]
It looks like EOF isn't being handled in the `Stream` implementation, if the underlying `AsyncRead` returns 0 bytes it will just be polled again and again in an infinite loop, sticking in a `dbg!` gives a stream of:

```
[src/framed_read.rs:88] Pin::new(&mut this.inner).poll_read(cx, &mut buf) = Ready(
    Ok(
        0,
    ),
)
[src/framed_read.rs:88] Pin::new(&mut this.inner).poll_read(cx, &mut buf) = Ready(
    Ok(
        0,
    ),
)
```

**Comment by matthunz** [comment]
Yeah good catch I'm still trying to decide what to do here. I was finding with a romio tcpstream I ran into a lot of null reads before the true EOF. I figured that handling that as an error was better left up to individual codec implementation (and handled with a timeout or etc).

**Comment by Nemo157** [comment]
If romio is returning 0 bytes before EOF then that’s a bug that needs fixing upstream.

In my case my codec has no way to know when end of stream is, it expects to just keep receiving delimited packets until the stream stops. The stream ending is also not an error condition, it just means the client has disconnected (which I then need to notice elsewhere by receiving `None` from the stream and deal with the disconnection).

**Comment by matthunz** [comment]
Just commited a fix: https://github.com/matthunz/futures-codec/commit/4db4314649fc3bbccb41d3f6a99f1e31d45cd8e9. When EOF is reached the stream will return `None` if there's nothing left in the buffer and `Err(UnexpectedEof)` if there is

**Comment by Nemo157** [comment]
Awesome, that makes a lot of sense. Thanks!
