### ISSUE TITLE
Depreciate crate in favor of tokio-codec

### ISSUE THREAD

**Issue by matthunz** [matthunz/futures-codec#12]
With [tokio-codec](https://github.com/tokio-rs/tokio/tree/master/tokio-codec) switching to futures 0.3 in master this crate might be made useless, unless anyone can think of a feature this crate should have that isn't covered by tokio.

@najamelan
@cbs228

**Comment by najamelan** [comment]
For sure one day tokio will be on  futures 0.3, but there's no telling when it will be stable. At that point it might be good to deprecate this crate. However in the mean-time, I think it's useful in development and testing, like I'm very glad `romio` exists for 6 months now, even though surely someday `tokio-tcp` will be futures 0.3 as well.

If it's not to much work, I would appreciate it if the Sink impl would get fixed, so we can keep experimenting with it until tokio_codec fully supports futures 0.3 AsyncRead/AsyncWrite.

I wouldn't necessarily invest heavily in new features, but just making sure that what's there works correctly, and maybe documenting that it probably will be superseded by tokio a some point would be great!

And thanks for sharing this code in the first place.

**Comment by matthunz** [comment]
You make a good point. I'll try to keep this around until tokio is stable as it looks like they're just starting to reimplement everything.

Also you're welcome. I'm glad someone's interested in my crate and especially thanks for all the support with it.
