### ISSUE TITLE
Unify framed transports with Transport

### ISSUE THREAD

**Issue by matthunz** [matthunz/futures-codec#14]
This crate has some redundancy in order to provide a good abstraction (such as [implementing `AsyncRead` for `Fuse`](https://github.com/matthunz/futures-codec/blob/a603ab31d49e2caa83eebafdc408c9780b8e97bc/src/framed.rs#L21)). However this does make for a nice api (e.g. `FramedWrite` cant be a `Stream`).

I propose [transport](https://github.com/matthunz/futures-codec/blob/transports/src/transport.rs) as a solution to this. Most of the adapters would be inside one struct which would enable us to reuse methods and trait implementations (like `Sink` and `Stream`).

You could then make a framed stream with `Transport::framed(io, codec)` or `Transport::framed_write(io, encoder)`

The branch is here:
https://github.com/matthunz/futures-codec/tree/transports

You guys have an opinion on this?
@najamelan @cbs228 @Nemo157

**Comment by cbs228** [comment]
Is your new composite type `Sink` or `Stream`? It appears that one can only access the underlying streams by reference. While I can see how this approach will streamline things, I am concerned that this will limit the opportunities for:

* Compositing `Framed` with generics that take `Sink`/`Stream`; or
* Using `Framed` with futures which consume their `Sink`/`Stream` by move.

The latter is a bit rarer these days, thankfully. Many futures take streams by `&mut` refs. But `SinkExt::fanout()` will consume a `Sink`, as does `SinkExt::left_sink()`.

I am actually not sure what the primary use-case is for split I/O types: i.e., types which are `AsyncWrite` but not `AsyncRead`, or vice-versa. I've seen tokio calls for splitting a socket into read and write halves, but I'm not sure how people use that. The only use-case I can think of immediately might be a `Cursor` to a `&'static [u8]`. If one can make such a thing, it would be rightfully be `AsyncRead` only.

**Comment by matthunz** [comment]
Oh well I haven't implemented `Sink` or `Stream` yet, just have those placeholders to demonstrate.

I definitely agree with you about streams being accessed by reference. I'm hoping to add the methods we have now, just generically in the `Transport` struct, so we can re use code. Basically the end goal is you should be able to use the library the same, getting an owned stream if needed.

First though the problem I'm still trying to figure out is whether exposing `Framed` as a type alias of `Transport` is weird to work with.

**Comment by cbs228** [comment]
Sounds good; I'm glad there will be an option for an owned stream. I look forward to seeing this when it gets closer to finished.

I generally aim to have a small API surface, which exposes as few types as possible to the user. Were you planning on exposing both `Transport` and various `Framed` aliases?

**Comment by najamelan** [comment]
I think I don't understand all of the implications of this, but if it makes the impl cleaner and it does not remove functionality, then it should be good!

For solving the issues with being able to move out the stream and sink, it would be good to provide a split method I think. There's still many combinators that take by value, like most methods on futures::StreamExt.

**Comment by oleid** [comment]
> I am actually not sure what the primary use-case is for split I/O types: i.e., types which are AsyncWrite but not AsyncRead, or vice-versa.

Maybe I missed something, however, consider this : you are reading a file, which gets decompressed via some async (de) compression create. The resulting object will only implement AsyncRead, not write.
