### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by cbs228** [matthunz/futures-codec#22]
Can you publish a new version of this crate to crates.io? I'd like a new release which contains #18.

It might also be a good idea to tag released versions with annotated tags (`git tag -a …`). GH will auto-detect these as "releases" and add them to your [releases](https://github.com/matthunz/futures-codec/releases) page.

**Comment by matthunz** [comment]
Sorry about the wait. Published and tagged with 41a239c14eb2fcaaed81ecd7b22af132613def07
