### ISSUE TITLE
Returning Ok(None) ends the stream?

### ISSUE THREAD

**Issue by goto-bus-stop** [matthunz/futures-codec#27]
I'm working on a Server-Sent Events library that uses futures_codec to decode an event stream line by line. Some servers send heartbeat messages as comments (lines starting with `:`), which should be discarded by the decoder. So it's possible to get a stream of input like:

```
:heartbeat signal

[10 seconds later]
:heartbeat signal

[10 seconds later]
:heartbeat signal
```

After parsing the `:heartbeat signal` lines and getting to the end of the current buffer, my parser returns `Ok(None)`, because there were no actual event messages in the input. At this point, FramedRead will return `Poll::Ready(None)` instead of `Poll::Pending`, thus ending the stream.

This test simulates the behaviour by emitting single bytes from an AsyncRead impl: https://github.com/goto-bus-stop/futures-codec/commit/3bebe0c7390639db45a3d0eff70ed0101e1661f7
The `a`s represent event messages, and `b`s represent comments that should be ignored. When reaching a `b`, the decoder returns Ok(None) and the stream is ended.

Is this the intended behaviour? I think ending the stream is a legitimate use case, but I'm not sure how to implement a parser that doesn't emit a message for every input correctly. I thought I could work around it by not consuming the comment lines from the `BytesMut` input until there is an actual event message, but that would require re-parsing those comment lines on every call to decode(), and the [`buffer.is_empty()` check](https://github.com/matthunz/futures-codec/blob/30a01deca260ab3cd347344eb4a0ecb0f21efe35/src/framed_read.rs#L128-L130) will return an error because the buffer isn't empty after the call to decode().

For my use case, returning `Poll::Pending` if the decoder return `Ok(None)` would be a solution. The decoder itself can then no longer decide to close the stream, unless the return value is changed from `Option<Self::Item>` to something like
```rust
enum DecodeResult<T> { // T = Self::Item
    Item(T),
    Pending, // no item here, need more data
    End, // done, close the input stream
}
```

**Comment by matthunz** [comment]
I know tokio had a `decode_eof` method in `Decoder` that's called when there are no bytes remaining in the stream. Would that solve your issue if you could then return `Poll::Pending` from that method?

**Comment by goto-bus-stop** [comment]
I think `decode_eof` is a bit different. It's called when the input stream ends. In this case, `futures-codec` is ending the _decoder_ stream when I return `Ok(None)` from my `decode()` implementation. With tokio-codec, returning `Ok(None)` indicates that the decoder needs more bytes from the input stream, but with futures-codec, it ends the stream. For me the tokio-codec behaviour is better, because the `decode()` implementation may be called multiple times with new data before it can return an `Ok(Some(item))`.

**Comment by goto-bus-stop** [comment]
Opened #28 with behaviour that would fit my use case—if nothing else, I hope it clarifies what I mean! :laughing:

**Comment by matthunz** [comment]
Oh gotcha, thanks for clearing that up! That definitely does sound like the desired behavior

**Comment by goto-bus-stop** [comment]
Was 0.3.4 released to crates.io? I only see [0.3.3](https://crates.io/crates/futures_codec/versions) there :speak_no_evil:
