### ISSUE TITLE
Update await in docs

### ISSUE THREAD

**Issue by Proximyst** [matthunz/futures-codec#5]
Given the new `.await` syntax [being stabilised in 1.36.0](https://blog.rust-lang.org/2019/07/04/Rust-1.36.0.html), the docs should move from `await!` to the new syntax.

**Comment by matthunz** [comment]
Thanks, updated the docs with https://github.com/matthunz/futures-codec/commit/5321040773e254caad70f0280a8a8c10b5c29c57
